#ifndef __WBA_POOL_CONFIG_H__
#define __WBA_POOL_CONFIG_H__

#include "wba_bitmanip.h"

#define WBA_POOL_CONFIG_TYPE unsigned int

#define WBA_POOL_CONFIG_BYTES (sizeof(WBA_POOL_CONFIG_TYPE))
#define WBA_POOL_CONFIG_SIZE (bitsof(WBA_POOL_CONFIG_TYPE))
#define WBA_POOL_CONFIG_OFFSET 0

#define WBA_POOL_SIZE_SIZE (WBA_POOL_CONFIG_SIZE / 2)
#define WBA_POOL_SIZE_OFFSET (WBA_POOL_CONFIG_OFFSET)
#define WBA_MAX_SIZE_SIZE ((WBA_POOL_CONFIG_SIZE - WBA_POOL_SIZE_SIZE) / 2)
#define WBA_MAX_SIZE_OFFSET (WBA_POOL_SIZE_OFFSET + WBA_POOL_SIZE_SIZE)
#define WBA_NUM_SECTIONS_SIZE WBA_MAX_SIZE_SIZE
#define WBA_NUM_SECTIONS_OFFSET (WBA_MAX_SIZE_OFFSET + WBA_MAX_SIZE_SIZE)

#define WBA_POOL_SIZE_MASK (WBA_GET_MASK(WBA_POOL_SIZE_SIZE))
#define WBA_MAX_SIZE_MASK (WBA_GET_MASK(WBA_MAX_SIZE_SIZE))
#define WBA_NUM_SECTIONS_MASK (WBA_GET_MASK(WBA_NUM_SECTIONS_SIZE))

#define WBA_POOL_SIZE_MASK_OFFSET (WBA_GET_MASK_OFFSET(WBA_POOL_SIZE_MASK, WBA_POOL_SIZE_OFFSET))
#define WBA_MAX_SIZE_MASK_OFFSET (WBA_GET_MASK_OFFSET(WBA_MAX_SIZE_MASK, WBA_MAX_SIZE_OFFSET))
#define WBA_NUM_SECTIONS_MASK_OFFSET (WBA_GET_MASK_OFFSET(WBA_NUM_SECTIONS_MASK, WBA_NUM_SECTIONS_OFFSET))

#define WBA_POOL_CONFIG_MASK ((WBA_POOL_CONFIG_TYPE)(WBA_POOL_SIZE_MASK_OFFSET | WBA_MAX_SIZE_MASK_OFFSET | WBA_NUM_SECTIONS_MASK_OFFSET))

#define WBA_GET_POOL_CONFIG(pool) (*((WBA_POOL_CONFIG_TYPE*)(pool + WBA_POOL_CONFIG_OFFSET)))

#define WBA_GET_POOL_SIZE(pool) (WBA_GET_VALUE(WBA_GET_POOL_CONFIG(pool), WBA_POOL_SIZE_MASK, WBA_POOL_SIZE_OFFSET))
#define WBA_GET_MAX_SIZE(pool) (WBA_GET_VALUE(WBA_GET_POOL_CONFIG(pool), WBA_MAX_SIZE_MASK, WBA_MAX_SIZE_OFFSET))
#define WBA_GET_NUM_SECTIONS(pool) (WBA_GET_VALUE(WBA_GET_POOL_CONFIG(pool), WBA_NUM_SECTIONS_MASK, WBA_NUM_SECTIONS_OFFSET))

#define WBA_GET_POOL_SIZE_MASKED_OFFSET_VALUE(val) (WBA_GET_MASKED_OFFSET_VALUE(val, WBA_POOL_SIZE_MASK, WBA_POOL_SIZE_OFFSET))
#define WBA_GET_MAX_SIZE_MASKED_OFFSET_VALUE(val) (WBA_GET_MASKED_OFFSET_VALUE(val, WBA_MAX_SIZE_MASK, WBA_MAX_SIZE_OFFSET))
#define WBA_GET_NUM_SECTIONS_MASKED_OFFSET_VALUE(val) (WBA_GET_MASKED_OFFSET_VALUE(val, WBA_NUM_SECTIONS_MASK, WBA_NUM_SECTIONS_OFFSET))


#endif /* __WBA_POOL_CONFIG_H__ */
